### ISSUE TITLE
from secret import header ImportError:

### ISSUE THREAD

**Issue by feifly329** [liutaihua/hot-samer#6]
如题:  
from secret import header
ImportError: cannot import name header

**Comment by liutaihua** [comment]
secret.py文件 因为涉及same应用的认证token，因此之前我隐去了。
我已经创建了一个空的secret.py文件

只有在拉取用户数据，和私信的时候需要这个token， 因此普通的帖子数据抓取即是空的secret.py文件也一样可以work

**Comment by feifly329** [comment]
恩,谢谢,享福了.
